### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by Immortalin** [yoshiquest/forge-clj#10]
If you tag releases, users can directly download them from github and you no longer have to provide links to dropbox.

**Comment by ryanhaney97** [comment]
Didn't know this, I'll have to take a look at this feature. Though I don't think it'll work anyways, since the things I'm providing are the already-compiled code.

**Comment by Immortalin** [comment]
Use continuous integration on push.

**Comment by ryanhaney97** [comment]
Hm, don't really know how to do this, and either way I already have a sub-program I wrote that updates the mod for me.

I'll close this issue for now, but if things start becoming inconvenient when uploading files, I'll reopen this. But for now, what I have works, so closed.

**Comment by Immortalin** [comment]
@yoshiquest there are better ways to doing this, both for long-term maintainability and security. See [this](https://docs.travis-ci.com/user/languages/java/) and [this](https://docs.travis-ci.com/user/deployment/releases/)

**Comment by Immortalin** [comment]
@yoshiquest see [this](https://github.com/yoshiquest/forge-clj/pull/17)
