### ISSUE TITLE
Stuff for you to replicate

### ISSUE THREAD

**Issue by Immortalin** [yoshiquest/forge-clj#11]
You mentioned on [minecraftforum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1206#c24440) that you wanted mods to replicate in order to test your abilities. Here's a [list](https://github.com/agaricusb/ForgeMod/wiki/List-of-Open-Source-Forge-Mods)

**Comment by ryanhaney97** [comment]
Heh, thanks. I've already seen this list. I don't think I'll be replicating mods as soon as I thought at the time, so I won't worry about this.
